-- AlterTable
ALTER TABLE "Book" ADD COLUMN "phase" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Book" ADD COLUMN "pagesTotal" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Book" ADD COLUMN "pagesDone" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Book" ADD COLUMN "textKey" TEXT;
